backend:
  name: git-gateway
  branch: main
  identity_url: https://vestibule.netlify.app/.netlify/identity
  gateway_url: https://vestibule.netlify.app/.netlify/git

site_url: https://vestibule.netlify.app
locale: en
media_folder: "images"
public_folder: "/images"
publish_mode: editorial_workflow

collections:
  - name: "versions"
    label: "Song Versions"
    folder: "changelogs"
    create: true
    slug: "{{fields.song | slugify}}-{{fields.version}}"
    format: "json"
    identifier_field: "song"
    fields:
      - { label: "Song Title", name: "song", widget: "string" }
      - { label: "Version Tag", name: "version", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Notes / Changelog", name: "notes", widget: "markdown" }
      - { label: "Audio File", name: "audio", widget: "file" }
