backend:
  name: git-gateway
  branch: main
media_folder: "images"
public_folder: "/images"
collections:
  - name: "versions"
    label: "Song Versions"
    folder: "changelogs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Song", name: "song", widget: "string" }
      - { label: "Version", name: "version", widget: "string" }
      - { label: "Notes", name: "notes", widget: "markdown" }
      - { label: "Audio File", name: "audio", widget: "file" }
      - { label: "Date", name: "date", widget: "datetime" }
